language: node_js
node_js:
  - '0.10'
before_install:
# CLOSURE COMPILER
  - sudo apt-get install git ant openjdk-7-jdk
  - git clone https://code.google.com/p/closure-compiler/
  - cd closure-compiler
  - ant
# COMPASS
  - gem update --system
  - gem install sass --version "=3.2.12"
  - gem install compass --version "=0.12.2"
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
