language: node_js
node_js:
  - '0.10'
  - '0.11'
before_install:
  - sudo apt-get update
  - sudo gem install sass
  - sudo gem install compass
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
